### ISSUE TITLE
Publish to General Registry

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#3]
Required:

- [x] Version number: no skips allowed. We need to decide if we want to start afresh (current [Project.toml](https://github.com/microsoft/Opticks.jl/blob/9100e1ef551791caa9d55f2fb56c5bbeef2154fc/Project.toml#L5) version is 0.2.8). Good reference [here](https://semver.org/).
- [x] Dependencies [#9]: via upper bounded `[compat]` entries in Project.toml, with a finite number of breaking releases - [CompatHelper](https://github.com/JuliaRegistries/CompatHelper.jl).
- [x] Installation [#7]: The package should be installable (`Pkg.add("PackageName")`), and loadable (`import PackageName`).
- [x] License: The package should have an [OSI-approved software license](https://opensource.org/licenses/alphabetical) located in the top-level directory of the package code, e.g. in a file named LICENSE or LICENSE.md.
- [x] Naming [#2]:
  - The package name should start with a capital letter, contain only ASCII alphanumeric characters, contain a lowercase letter, be at least 5 characters long, and should not start with "Ju" or contain the string "julia".
  - The [Damerau–Levenshtein](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance) distance between the package name and the name of any existing package must be at least 3.
  - The Damerau–Levenshtein distance between the lowercased version of a package name and the lowercased version of the name of any existing package must be at least 2.
  - A visual distance from [VisualStringDistances.jl](https://github.com/ericphanson/VisualStringDistances.jl) between the package name and any existing package must exceed a certain a hand-chosen threshold (currently 2.5).

Highly recommended:

- [x] [Registrator.jl](https://github.com/JuliaRegistries/Registrator.jl) [#10]: via [Github App](https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app) or [web interface](https://github.com/JuliaRegistries/Registrator.jl#via-the-web-interface).
- [x] [TagBot](https://github.com/JuliaRegistries/TagBot) [#8]: automatically tags a release in your repository after the new release of your package is merged into the registry.

Optional:

- [x] Automated testing [#4]
- [x] Code coverage [#11]
- [x] Deployed docs [#6]

**Comment by alfredclwong** [comment]
[![](https://img.shields.io/badge/docs-dev-blue.svg)](https://microsoft.github.io/OpticSim.jl/dev/)

**Comment by alfredclwong** [comment]
[![](https://img.shields.io/badge/docs-dev-blue.svg)](https://microsoft.github.io/OpticSim.jl/dev/)
